# Generated by Django 4.0 on 2022-05-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.ImageField(upload_to='manga/static/manga/pages/')),
            ],
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='pages',
        ),
        migrations.AddField(
            model_name='chapter',
            name='chapter_pages',
            field=models.ManyToManyField(blank=True, related_name='chapter_img', to='manga.Pages'),
        ),
    ]
