# Generated by Django 4.0 on 2022-05-18 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_pages_remove_chapter_pages_chapter_chapter_pages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pages',
            new_name='Page',
        ),
    ]
