# Generated by Django 4.0 on 2022-05-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0003_rename_pages_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='chapter_pages',
        ),
        migrations.AddField(
            model_name='chapter',
            name='page',
            field=models.ImageField(null=True, upload_to='manga/static/manga/pages/'),
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
