# Generated by Django 4.0 on 2022-05-18 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0004_remove_chapter_chapter_pages_chapter_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='page',
            field=models.FileField(default=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='PostPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages', models.FileField(upload_to='manga/static/manga/pages/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='manga.chapter')),
            ],
        ),
    ]
