# Generated by Django 4.0 on 2022-05-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0006_remove_chapter_page_alter_postpage_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='pages',
            field=models.ImageField(upload_to='manga/static/manga/pages/'),
        ),
    ]
