# Generated by Django 4.0 on 2022-06-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0007_alter_postpage_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postpage',
            name='pages',
            field=models.ImageField(upload_to='manga/pages/'),
        ),
    ]
